#!/bin/sh

echo "set terminal png; \
set output '$1'; \
set style data histograms; \
set key off; \
set boxwidth 3.00; \
set style fill solid 1.00 border -1; \
set logscale y; \
set xrange [0:]; \
plot '$2' u 2" | gnuplot
